// SPDX-License-Identifier: Apache-2.0
//
// LYF2-261: litellm and lyfe-worker, migrated off Railway into the same VPC/cluster `BackEnd`
// already created for the Medplum server. Neither service needs its own VPC, ECS cluster, or
// RDS/Redis -- they attach to BackEnd's.
//
// litellm is Medplum's own documented way to point the `$ai` operation at Bedrock (it only
// speaks the OpenAI chat-completions wire format; see packages/docs/docs/ai/ai-operation.md),
// so this is not a parallel implementation -- it is reached only by the Medplum server, over
// Cloud Map private DNS, with no ALB and no public domain.
//
// lyfe-worker calls Bedrock directly for embeddings (src/rag/bedrock.ts) and does not go through
// litellm at all. It needs a *public* ALB because it registers Inngest's classic inbound
// `serve()` handler -- Inngest Cloud calls into `/api/inngest` to invoke each step, which is not
// Inngest Connect's outbound-only mode -- and because the browser app calls it directly for bulk
// import and RAG.
import type { MedplumInfraConfig } from '@medplum/core';
import {
  Duration,
  RemovalPolicy,
  aws_ec2 as ec2,
  aws_ecs as ecs,
  aws_elasticloadbalancingv2 as elbv2,
  aws_iam as iam,
  aws_logs as logs,
  aws_route53 as route53,
  aws_route53_targets as targets,
  aws_secretsmanager as secretsmanager,
  aws_servicediscovery as servicediscovery,
  aws_wafv2 as wafv2,
} from 'aws-cdk-lib';
import { Repository } from 'aws-cdk-lib/aws-ecr';
import { Construct } from 'constructs';
import type { BackEnd } from './backend';
import { buildWaf } from './waf';

export interface LyfeServicesConfig {
  /** litellm's container image. Defaults to the same image Railway ran. */
  litellmImage?: string;
  /** Passed to litellm's `--model`. Defaults to the cross-region inference profile Railway used. */
  litellmModel?: string;
  litellmCpu?: number;
  litellmMemory?: number;

  /**
   * The region Bedrock (and Textract, for the worker) is actually called in -- independent of
   * `config.region`, which is where the compute and VPC live. Bedrock is not available in every
   * region (notably not us-west-1), and the "global" cross-region inference profile Railway used
   * was provisioned in us-east-1, so that stays the default here too. The ECS task's outbound
   * HTTPS call to `bedrock-runtime.<bedrockRegion>.amazonaws.com` works from any region with
   * internet egress -- the compute does not need to run in a Bedrock region.
   */
  bedrockRegion?: string;

  /** The lyfe-worker container image -- built from docker/worker.Dockerfile and pushed to ECR. */
  workerImage: string;
  workerCpu?: number;
  workerMemory?: number;
  workerDesiredCount?: number;
  /** Public hostname for Inngest's inbound webhook and the browser app's bulk-import/RAG calls. */
  workerDomainName: string;
  /** ACM cert for the worker's ALB. Must be issued in `config.region`, not us-east-1. */
  workerSslCertArn: string;
  /** Comma-separated browser origins allowed to call /api/imports/bulk and /api/rag/*. */
  workerAllowedOrigins: string;
  /** The Medplum ClientApplication id the worker authenticates as (M2M). Not a secret. */
  workerMedplumClientId: string;
  /**
   * ARN of a Secrets Manager secret holding the worker's sensitive values as one JSON blob, with
   * keys MEDPLUM_CLIENT_SECRET, LYFE_CREDENTIAL_ENCRYPTION_KEY, INNGEST_SIGNING_KEY,
   * INNGEST_EVENT_KEY, and RAG_DATABASE_URL. Created once, out of band -- see
   * packages/cdk/README.md -- because these values must match what Medplum's project secrets,
   * Inngest's dashboard, and the Aurora `lyfe_rag` role already hold; none of them can be
   * generated by this stack.
   */
  workerSecretsArn: string;
  workerSummaryDebouncePeriod?: string;
}

const DEFAULT_LITELLM_IMAGE = 'ghcr.io/berriai/litellm:main-stable';
const DEFAULT_LITELLM_MODEL = 'bedrock/global.anthropic.claude-sonnet-4-6';
const DEFAULT_BEDROCK_REGION = 'us-east-1';
const LITELLM_PORT = 4000;
const WORKER_PORT = 3020;

export class LyfeServices extends Construct {
  litellmService: ecs.FargateService;
  litellmSecurityGroup: ec2.SecurityGroup;
  workerService: ecs.FargateService;
  workerSecurityGroup: ec2.SecurityGroup;
  workerLoadBalancer: elbv2.ApplicationLoadBalancer;

  constructor(scope: Construct, config: MedplumInfraConfig, lyfeConfig: LyfeServicesConfig, backEnd: BackEnd) {
    super(scope, 'LyfeServices');

    const namespace = new servicediscovery.PrivateDnsNamespace(this, 'InternalNamespace', {
      name: 'medplum.internal',
      vpc: backEnd.vpc,
    });

    const litellm = this.createLiteLLM(config, lyfeConfig, backEnd, namespace);
    this.litellmService = litellm.service;
    this.litellmSecurityGroup = litellm.securityGroup;

    const worker = this.createWorker(config, lyfeConfig, backEnd);
    this.workerService = worker.service;
    this.workerSecurityGroup = worker.securityGroup;
    this.workerLoadBalancer = worker.loadBalancer;
  }

  private createLiteLLM(
    config: MedplumInfraConfig,
    lyfeConfig: LyfeServicesConfig,
    backEnd: BackEnd,
    namespace: servicediscovery.PrivateDnsNamespace
  ): { service: ecs.FargateService; securityGroup: ec2.SecurityGroup } {
    const bedrockRegion = lyfeConfig.bedrockRegion ?? DEFAULT_BEDROCK_REGION;

    const taskRole = new iam.Role(this, 'LiteLLMTaskRole', {
      assumedBy: new iam.ServicePrincipal('ecs-tasks.amazonaws.com'),
    });
    // Cross-region inference profiles are addressed by a profile id, not a single model ARN --
    // invocation can land on any underlying foundation model the profile routes to, so the grant
    // has to cover both the profile itself and the foundation models it may dispatch to.
    taskRole.addToPolicy(
      new iam.PolicyStatement({
        actions: ['bedrock:InvokeModel', 'bedrock:InvokeModelWithResponseStream'],
        resources: [
          `arn:aws:bedrock:${bedrockRegion}:${config.accountNumber}:inference-profile/*`,
          'arn:aws:bedrock:*::foundation-model/*',
        ],
      })
    );

    const masterKey = new secretsmanager.Secret(this, 'LiteLLMMasterKey', {
      description: 'litellm bearer token -- also set as the Medplum project secret OPENAI_API_KEY',
      generateSecretString: { excludePunctuation: true, passwordLength: 40 },
    });

    const taskDefinition = new ecs.FargateTaskDefinition(this, 'LiteLLMTaskDefinition', {
      memoryLimitMiB: lyfeConfig.litellmMemory ?? 1024,
      cpu: lyfeConfig.litellmCpu ?? 512,
      taskRole,
    });

    const logGroup = new logs.LogGroup(this, 'LiteLLMLogGroup', {
      logGroupName: `/ecs/medplum/${config.name}-litellm`,
      removalPolicy: RemovalPolicy.DESTROY,
    });

    taskDefinition.addContainer('LiteLLMContainer', {
      image: containerImageFor(this, config, lyfeConfig.litellmImage ?? DEFAULT_LITELLM_IMAGE, 'LiteLLM'),
      command: [
        '--model',
        lyfeConfig.litellmModel ?? DEFAULT_LITELLM_MODEL,
        '--host',
        '0.0.0.0',
        '--port',
        String(LITELLM_PORT),
      ],
      portMappings: [{ containerPort: LITELLM_PORT }],
      logging: new ecs.AwsLogDriver({ logGroup, streamPrefix: 'litellm' }),
      environment: {
        AWS_REGION: bedrockRegion,
      },
      secrets: {
        LITELLM_MASTER_KEY: ecs.Secret.fromSecretsManager(masterKey),
      },
    });

    const securityGroup = new ec2.SecurityGroup(this, 'LiteLLMSecurityGroup', {
      vpc: backEnd.vpc,
      allowAllOutbound: true,
      description: 'litellm: inbound from the Medplum server only',
    });
    securityGroup.addIngressRule(
      backEnd.fargateSecurityGroup,
      ec2.Port.tcp(LITELLM_PORT),
      'Medplum server $ai operation'
    );

    const service = new ecs.FargateService(this, 'LiteLLMFargateService', {
      cluster: backEnd.ecsCluster,
      taskDefinition,
      desiredCount: 1,
      assignPublicIp: false,
      vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS },
      securityGroups: [securityGroup],
      healthCheckGracePeriod: Duration.minutes(2),
      minHealthyPercent: 100,
      cloudMapOptions: {
        cloudMapNamespace: namespace,
        name: 'litellm',
        dnsRecordType: servicediscovery.DnsRecordType.A,
      },
    });

    return { service, securityGroup };
  }

  private createWorker(
    config: MedplumInfraConfig,
    lyfeConfig: LyfeServicesConfig,
    backEnd: BackEnd
  ): { service: ecs.FargateService; securityGroup: ec2.SecurityGroup; loadBalancer: elbv2.ApplicationLoadBalancer } {
    const bedrockRegion = lyfeConfig.bedrockRegion ?? DEFAULT_BEDROCK_REGION;

    const taskRole = new iam.Role(this, 'WorkerTaskRole', {
      assumedBy: new iam.ServicePrincipal('ecs-tasks.amazonaws.com'),
    });
    taskRole.addToPolicy(
      new iam.PolicyStatement({
        actions: ['bedrock:InvokeModel'],
        resources: [`arn:aws:bedrock:${bedrockRegion}::foundation-model/amazon.titan-embed-text-v2:0`],
      })
    );
    taskRole.addToPolicy(
      new iam.PolicyStatement({
        // Textract has no resource-level permissions -- every action requires `Resource: '*'`.
        actions: ['textract:AnalyzeDocument'],
        resources: ['*'],
      })
    );

    const workerSecrets = secretsmanager.Secret.fromSecretCompleteArn(
      this,
      'WorkerSecrets',
      lyfeConfig.workerSecretsArn
    );
    workerSecrets.grantRead(taskRole);

    const taskDefinition = new ecs.FargateTaskDefinition(this, 'WorkerTaskDefinition', {
      memoryLimitMiB: lyfeConfig.workerMemory ?? 1024,
      cpu: lyfeConfig.workerCpu ?? 512,
      taskRole,
    });

    const logGroup = new logs.LogGroup(this, 'WorkerLogGroup', {
      logGroupName: `/ecs/medplum/${config.name}-worker`,
      removalPolicy: RemovalPolicy.DESTROY,
    });

    taskDefinition.addContainer('WorkerContainer', {
      image: containerImageFor(this, config, lyfeConfig.workerImage, 'Worker'),
      portMappings: [{ containerPort: WORKER_PORT }],
      logging: new ecs.AwsLogDriver({ logGroup, streamPrefix: 'worker' }),
      environment: {
        MEDPLUM_BASE_URL: config.baseUrl ?? `https://${config.apiDomainName}/`,
        MEDPLUM_CLIENT_ID: lyfeConfig.workerMedplumClientId,
        PORT: String(WORKER_PORT),
        ALLOWED_ORIGINS: lyfeConfig.workerAllowedOrigins,
        AWS_REGION: bedrockRegion,
        SUMMARY_DEBOUNCE_PERIOD: lyfeConfig.workerSummaryDebouncePeriod ?? '10m',
      },
      secrets: {
        MEDPLUM_CLIENT_SECRET: ecs.Secret.fromSecretsManager(workerSecrets, 'MEDPLUM_CLIENT_SECRET'),
        LYFE_CREDENTIAL_ENCRYPTION_KEY: ecs.Secret.fromSecretsManager(workerSecrets, 'LYFE_CREDENTIAL_ENCRYPTION_KEY'),
        INNGEST_SIGNING_KEY: ecs.Secret.fromSecretsManager(workerSecrets, 'INNGEST_SIGNING_KEY'),
        INNGEST_EVENT_KEY: ecs.Secret.fromSecretsManager(workerSecrets, 'INNGEST_EVENT_KEY'),
        RAG_DATABASE_URL: ecs.Secret.fromSecretsManager(workerSecrets, 'RAG_DATABASE_URL'),
      },
    });

    const albSecurityGroup = new ec2.SecurityGroup(this, 'WorkerAlbSecurityGroup', {
      vpc: backEnd.vpc,
      allowAllOutbound: true,
      description: 'lyfe-worker ALB: public HTTPS for Inngest callbacks and the browser app',
    });
    albSecurityGroup.addIngressRule(ec2.Peer.anyIpv4(), ec2.Port.tcp(443), 'Public HTTPS');

    const serviceSecurityGroup = new ec2.SecurityGroup(this, 'WorkerSecurityGroup', {
      vpc: backEnd.vpc,
      allowAllOutbound: true,
      description: 'lyfe-worker: inbound from its own ALB only',
    });
    serviceSecurityGroup.addIngressRule(albSecurityGroup, ec2.Port.tcp(WORKER_PORT), 'Worker ALB');

    if (backEnd.rdsCluster) {
      backEnd.rdsCluster.connections.allowDefaultPortFrom(serviceSecurityGroup, 'lyfe-worker lyfe_rag schema');
    }

    const service = new ecs.FargateService(this, 'WorkerFargateService', {
      cluster: backEnd.ecsCluster,
      taskDefinition,
      desiredCount: lyfeConfig.workerDesiredCount ?? 1,
      assignPublicIp: false,
      vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS },
      securityGroups: [serviceSecurityGroup],
      healthCheckGracePeriod: Duration.minutes(2),
      minHealthyPercent: 100,
    });
    if (backEnd.rdsCluster) {
      service.node.addDependency(backEnd.rdsCluster);
    }

    const targetGroup = new elbv2.ApplicationTargetGroup(this, 'WorkerTargetGroup', {
      vpc: backEnd.vpc,
      port: WORKER_PORT,
      protocol: elbv2.ApplicationProtocol.HTTP,
      healthCheck: {
        path: '/health',
        interval: Duration.seconds(30),
        timeout: Duration.seconds(5),
        healthyThresholdCount: 2,
        unhealthyThresholdCount: 5,
      },
      targets: [service],
    });

    const loadBalancer = new elbv2.ApplicationLoadBalancer(this, 'WorkerLoadBalancer', {
      vpc: backEnd.vpc,
      internetFacing: true,
      http2Enabled: true,
      securityGroup: albSecurityGroup,
    });

    loadBalancer.addListener('WorkerHttpsListener', {
      port: 443,
      certificates: [{ certificateArn: lyfeConfig.workerSslCertArn }],
      sslPolicy: elbv2.SslPolicy.RECOMMENDED_TLS,
      defaultAction: elbv2.ListenerAction.forward([targetGroup]),
    });

    const waf = buildWaf(this, 'WorkerWAF', `${config.stackName}-WorkerWAF`, 'REGIONAL', undefined, undefined, undefined);
    new wafv2.CfnWebACLAssociation(this, 'WorkerLoadBalancerAssociation', {
      resourceArn: loadBalancer.loadBalancerArn,
      webAclArn: waf.attrArn,
    });

    const hostedZone = route53.HostedZone.fromLookup(this, 'WorkerHostedZone', {
      domainName: config.hostedZoneName ?? config.domainName.split('.').slice(-2).join('.'),
    });

    new route53.ARecord(this, 'WorkerDnsRecord', {
      zone: hostedZone,
      recordName: lyfeConfig.workerDomainName,
      target: route53.RecordTarget.fromAlias(new targets.LoadBalancerTarget(loadBalancer)),
    });

    return { service, securityGroup: serviceSecurityGroup, loadBalancer };
  }
}

/**
 * Resolves a container image the same way `BackEnd`'s private `getContainerImage` does: an ECR
 * URI in this account/region becomes a CDK-managed `Repository` reference (which auto-grants the
 * task's execution role pull access), anything else is a plain registry image. Duplicated rather
 * than exported from `BackEnd` because that method is private to keep upstream's class surface
 * unchanged.
 */
function containerImageFor(
  scope: Construct,
  config: MedplumInfraConfig,
  imageUri: string,
  idPrefix: string
): ecs.ContainerImage {
  const ecrImageUriRegex = new RegExp(
    `^${config.accountNumber}\\.dkr\\.ecr\\.${config.region}\\.amazonaws\\.com/(.*)[:@](.*)$`
  );
  const match = ecrImageUriRegex.exec(imageUri);
  if (match) {
    const [, repoName, tag] = match;
    const repo = Repository.fromRepositoryArn(
      scope,
      `${idPrefix}ImageRepo`,
      `arn:aws:ecr:${config.region}:${config.accountNumber}:repository/${repoName}`
    );
    return ecs.ContainerImage.fromEcrRepository(repo, tag);
  }
  return ecs.ContainerImage.fromRegistry(imageUri);
}
